# Generated by Django 4.2.2 on 2023-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_credititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
