# Generated by Django 4.2.2 on 2023-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_creditnote_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='adjustment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
