# Generated by Django 4.2.2 on 2023-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_alter_creditnote_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
