# Generated by Django 4.2.2 on 2023-09-14 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_alter_creditnote_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer'),
        ),
    ]
