# Generated by Django 4.2.2 on 2023-09-18 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0007_alter_creditnote_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditnote_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('creditnote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.creditnote')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
