# Generated by Django 4.2.2 on 2023-09-18 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0008_creditnote_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditnote_doc_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('document', models.FileField(upload_to='image/')),
                ('creditnote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.creditnote')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
