# Generated by Django 4.2.2 on 2023-09-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_creditnote_doc_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
