# Generated by Django 4.2.2 on 2023-09-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_creditnote_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credititem',
            name='item_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem'),
        ),
    ]
